### ISSUE TITLE
incompatibility with Gazebo7.0.0

### ISSUE THREAD

**Issue by joaobrittoneto** [rock-gazebo/simulation-orogen-rock_gazebo#10]
[‘class gazebo::sensors::ImuSensor’ has no member named SetWorldToReferenceOrientation’.](https://github.com/rock-gazebo/simulation-orogen-rock_gazebo/commit/4d94184521bedc661c6d188898ef48f1d4de955d#diff-8782f0f1dc6de9a84e56455a999d9c3dR59)
Using Gazebo7.0.0, from [ubuntu packages](https://packages.ubuntu.com/xenial/science/gazebo7). I think it becomes available in Gazebo7.2.0.

There are some problems with other packages using sdformat5, like [gui/control_ui](https://github.com/rock-gui/gui-control_ui/commit/7ad6f9e4aea865f9bd1f153a5fefadce51917be4).

**Comment by doudou** [comment]
Sorry @joaobrittoneto, I actually missed that one.

I'm fixing the G7 issue in #14

If using Gazebo 7, one should also use sdformat4

**Comment by doudou** [comment]
I'm closing this ... I don't think we'll spend time fixing it. We would welcome a pull request for it, though, if you so feel inclined.
