### ISSUE TITLE
ModelTask::readExportedJointCmd accepts only pure pure effort, position or speed cmds

### ISSUE THREAD

**Issue by alcantara09** [rock-gazebo/simulation-orogen-rock_gazebo#6]
When trying to send a joint command with position, speed and accelerations data, the model task raise a INVALID_JOINT_COMMAND exception.

In order to send this type of joint cmd, I worked around the problem relaxing this restriction in the Modeltask class. Doing so I was able to run the desired trajectory in my manipulator. 

Which is the reason to limit the joint cmd to pure mode only? Am I doing something conceptually wrong or this is a bug?

**Comment by doudou** [comment]
This is the only way to detect the intent of the writer based on the JointState contents. I personally very much prefer this over having even more flags.

In any case, what you propose here - auto-detecting the intent based on some built-in priority rules - would not be acceptable. If we really wanted to allow for more fields to be filled, we would need to add a property to the component.
